INSERT INTO users (username,password,permissions,created_at,updated_at) VALUES 
('DavidBea','pregunta2','YES',NOW(),NOW()),
('SebaSaez','pregunta2','YES',NOW(),NOW()),
('CGonzalez','pregunta2','YES',NOW(),NOW());

INSERT INTO questions (category,description,option1,option2,option3,option4,created_at,updated_at) VALUES
('DEPORTES','¿Cuántos puntos vale un tiro libre encestado en baloncesto?','1','2','3','Depende',NOW(),NOW()),
('DEPORTES','¿Cuánto dura un partido de fútbol?','90"','45"','75"','80"',NOW(),NOW()),
('DEPORTES','¿Dónde se inventó el tenis de mesa?','Inglaterra','China','Japón','Corea del Sur',NOW(),NOW()),
('DEPORTES','Si durante una mano de Póker me tocan 3 cartas del mismo valor, ¿qué jugada tengo?','Trio','Doble Par','Full','Par',NOW(),NOW()),
('DEPORTES','¿Quién ganó cuatro mundiales consecutivos de Fórmula 1?','Sebastian Vettel','Fernando Alonso','Lewis Hamilton','kimi Raikkonen',NOW(),NOW()),
('DEPORTES','Cuando y contra quién perdio la Seleccion Argentina la primer final del campeonato mundial de fútbol?','30 de julio 1930 contra Uruguay','30 de julio de 1930 contra Brasil','30 de julio de 1934 contra Alemania','30 de julio 1926 contra Holanda',NOW(),NOW()),
('DEPORTES','Despues de Cristiano Ronaldo y Lionel Messi, quien ha marcado mas tantos en la UEFA Champions League?','Raúl González','Henry','Van Nistelrooy','Ibrahimović',NOW(),NOW()),
('DEPORTES','¿Que entrenador ha dirigido mas partidos en la UEFA Champions League?','Alex Ferguson','Arséne Wenger','José Mourinho','Carlo Ancelotti',NOW(),NOW()),
('DEPORTES','¿Cuales de estos jugadores han disputado mas partidos en la UEFA Champions League?','Cristiano Ronaldo','Andrés Iniesta','Xavi Alonso','Lionel Messi',NOW(),NOW()),
('DEPORTES','¿Que equipo suma mas presencias en la UEFA Champions League?','Reald Madrid','Manchester United','Barcelona FC','Bayern Munich',NOW(),NOW()),
('DEPORTES','¿Quien es el jugador mas joven en debutar en la historia del torneo de la UEFA Champions League?','Babayaro(Anderlecht)','Fabregas(Arsenal)','Halilović(Dínamo de Zagreb)','Tielemans(Anderlecth)',NOW(),NOW()),
('DEPORTES','¿Tres equipos ganaron el título en su debut en el formato Champions League. ¿Cuáles fueron?','Marsella, Ajax y Juventus','Juventus, Estrella Roja y Bayern','Milan, Barcelona y Juventus','Marsella, Milan y Barcelona',NOW(),NOW()),
('DEPORTES','¿Que equipo tiene mas copas mundiales?','Italia','Uruguay','Inglaterra','Chile',NOW(),NOW()),
('DEPORTES','¿Quien es el cuadro con mas libertadores de America?','Independiente de Argentina','Santos de Brasil','Peñarol de Chile','Boca Juniors de Argentina',NOW(),NOW()),
('DEPORTES','¿Quien es el maximo goleador en copas mundiales??','Ronaldo (Brasil)','Van Nistelrooy (Holanda)','Neymar (Brasil)','Messi(Argentina)',NOW(),NOW()),
('DEPORTES','¿Cuales de estos Campeonatos juega un equipo Europeo?','SuperCopa UEFA','Copa Libertadores','Copa Sudamericana','Superliga Argentina',NOW(),NOW()),
('DEPORTES','¿Cuantos equipos participan en un Mundial?','32','28','36','40',NOW(),NOW()),
('DEPORTES','¿A que selección pertenece el jugador Arjen Robben?','Holanda','Francia','Inglaterra','Suecia',NOW(),NOW()),
('DEPORTES','¿A que selección pertenece el jugador Thiago Alcántara?','Italia','Alemania','Inglaterra','Chile',NOW(),NOW()),
('DEPORTES','¿A que selección pertenece el jugador Alexis Sánchez?','Chile','Argentina','Brasil','Italia',NOW(),NOW()),
('DEPORTES','¿A que selección pertenece el jugador Thiago Alcántara?','España','Alemania','Inglaterra','Chile',NOW(),NOW()),
('DEPORTES','¿Quién ganó el mundial de 1974?','Alemania','Argenina','Inglaterra','Brasil',NOW(),NOW()),
('DEPORTES','¿Contra qué selección Lionel Messi convirtió su primer gol oficial con la camiseta de la selección Argentina?','Croacia','Bolivia','Serbia y Montenegro','Venezuela',NOW(),NOW()),
('DEPORTES','¿Frente a que equipo marcó su primer gol el Kun Agüero con el Atletico de Madrid ?','Bilbao','Betis','Celta','Osasuna',NOW(),NOW()),
('DEPORTES','¿Quién ganó la Liga de Campeones de 1993?',' Olympique de Marsella','Barcelona','Bayern Munich','Real Madrid',NOW(),NOW()),
('DEPORTES','En qué debuto equipo Diego Armando Maradona?','Argentinos','Boca Juniors','River PLate','San Lorenzo de Almagro',NOW(),NOW()),
('DEPORTES','¿Donde nació Lionel Messi?','Santa Fe','Buenos Aires','Cordoba','Mendoza',NOW(),NOW()),
('DEPORTES','¿En la actualidad, quien es el arquero de Argentina?','Romero','Andujar','Barovero','Orion',NOW(),NOW()),
('DEPORTES','¿Donde hizo las inferiores Lionel Messi?','Newells Old Boys','Boca Juniors','Gimnasia de la Plata','Atlético Rafalela',NOW(),NOW()),
('DEPORTES','¿Cual es el país de origen del Fútbol?','China','Qatar','Nueva zelanda','Dinamarca',NOW(),NOW()),
('DEPORTES','¿Quién inventó la expresion "Jogo bonito"?','Pelé','Ronaldinho','Emanuel Ginobilli','Juan Martin del Potro',NOW(),NOW()),
('DEPORTES','¿Donde se fabrican la mayoria de las unidades de Futbol?','Pakistán','Estados Unidos','Francia','Japón',NOW(),NOW()),
('DEPORTES','¿De qué equipo era aficionado Bin Laden?','Arsenal','PSG','Manchester City','Atlético Madrid',NOW(),NOW()),
('DEPORTES','¿Qué deporte está relacionado a Roger Federer?','Tenis','Fútbol','Basquet','Rugby',NOW(),NOW()),
('DEPORTES','¿En qué deporte se puede ganar la “Copa Davis”?','Tenis','Polo','Truco','Voley',NOW(),NOW()),
('DEPORTES','El equipo de Rugby conocido como “All Blacks”, ¿de qué país es originario?','Nueva Zelanda','Estados Unidos','Australia','Japón',NOW(),NOW()),
('DEPORTES','¿Cuál de los siguientes deportistas no ha sido futbolista?','Rubens Barrichello','Thierry Henry','David Beckham','Ruben Baraja',NOW(),NOW()),
('DEPORTES','¿Cuál de los siguientes estilos de natación es más rápido?','Crawl','Espalda','Mariposa','Braza',NOW(),NOW()),
('DEPORTES','¿Cuál de los siguientes aparatos no se usan en la Gimnasia Rítmica?','El triángulo','La cuerda','La cinta','La pelota',NOW(),NOW()), 
('DEPORTES','¿Quién ganó el Tour de Francia en 2007?','Alberto Contador','Lance Armstrong','Miguel Induráin','Alexander Vinokourov',NOW(),NOW()),
('DEPORTES','¿En qué equipo de Formula 1 corría Michael Schumacher?','Ferrari','McLaren','Toyota','Renault',NOW(),NOW()),
('DEPORTES','¿A que selección pertenece el jugador Cristiano Ronaldo?','Portugal','Inglaterra','Rusia','Italia',NOW(),NOW()),
('DEPORTES','¿A que selección pertenece el jugador Lionel Messi?','Argentina','Uruguay','Peru','Chile',NOW(),NOW()),
('DEPORTES','¿Cuánto dura un partido de baloncesto?','40 minutos','1 hora','20 minutos','80 minutos',NOW(),NOW()),
('DEPORTES','¿Qué arma no se utiliza en esgrima?','La daga','La espada','El florete','El sable',NOW(),NOW()),
('DEPORTES','¿Cuántos puntos hace falta para ganar un juego en el Ping Pong?','21','11','9','15',NOW(),NOW()),
('DEPORTES','¿Qué medalla Olímpica no existe?','Cobre','Plata','Bronce','Oro',NOW(),NOW()),
('ENTRETENIMIENTO','¿En qué año se estreno el Rey León?','1994','1990','1992','1995',NOW(),NOW()),
('ENTRETENIMIENTO','¿En la pelicula, El rey león, cuantos hijos tienen Simba y Nala?','3','5','1','6',NOW(),NOW()),
('ENTRETENIMIENTO','¿En la pelicula, El rey león, quien es Rafiki?','Un orangután','Un mandril','Un babuino','Un chimpancé',NOW(),NOW()),
('ENTRETENIMIENTO','¿En Harry Potter, cual es el número de la cámara donde estaba guardada la Piedra Filosofal','714','777','315','694',NOW(),NOW()),
('ENTRETENIMIENTO','¿Cual fue el nombre de la infancia de Axel Rose?','William Bruce Bailey','Bruce Rose','Axel Bruce','Willy Axel',NOW(),NOW()),
('ENTRETENIMIENTO','¿El nombre real del cantante Maluma es ..','Juan Luis Londoño','Juan Carlos Rivera','Sergio Montenegro','Luis Villalba',NOW(),NOW()),
('ENTRETENIMIENTO','¿El superhéroe favorito eminem es..','Spiderman','Superman','Batman','Thor',NOW(),NOW()),
('ENTRETENIMIENTO','¿En que cómic aparece el cantante de rap Eminem?','Iron Man','Superman','Punisher','Thor',NOW(),NOW()),
('ENTRETENIMIENTO','¿Cual es el personaje mas pequeño de la banda Gorillaz','2D','Noodle','Murdoc','Russel',NOW(),NOW()),
('ENTRETENIMIENTO','¿Cual es el principal de la banda Gorilazz?','Russel','2D','Murdoc','Otro',NOW(),NOW()),
('ENTRETENIMIENTO','¿Cual fue la primer cancion de la banda Rombai?','Locuras contigo','Yo tambien','Curiosidad','Enamorarnos no',NOW(),NOW()),
('ENTRETENIMIENTO','¿En que año se formó la banda Rombai?','2015','2010','2012','2013',NOW(),NOW()),
('ENTRETENIMIENTO','¿En que año se funda la banda de cumbia cheta Marama?','2015','2012','2014','2016',NOW(),NOW()),
('ENTRETENIMIENTO','¿Cual es la primer canción escrita por los Guns N Roses?','Reckless Life','Welcome to the jungle','November Rain','Back off Bitch',NOW(),NOW()),
('ENTRETENIMIENTO','¿Cual es el principal de la banda Gorilazz?','Russel','2D','Murdoc','Otro',NOW(),NOW()),
('ENTRETENIMIENTO','¿De qué distrito es Katniss de Los juegos del hambre?','Distrito 12','Distrito 3','Distrito 2','Distrito 9',NOW(),NOW()),
('ENTRETENIMIENTO','¿Qué grupo cómico dobló al español a los protagonistas de “Shrek”?','Cruz y Raya','Tip & Coll','Martes & 13','Los Morancos',NOW(),NOW()),
('ENTRETENIMIENTO','¿Quien es el protagonista de la saga "Rocky"?','Silvester Stallone','Jason Statham','Bruce Lee','Arnold Schwarzernegger',NOW(),NOW()),
('ENTRETENIMIENTO','¿Cuantos premios Oscar consiguio el actor Leonardo DiCaprio?','1','Ninguno','3','2',NOW(),NOW()),
('ENTRETENIMIENTO','¿Quién es Bella en la saga "Crepúsculo"?','Kristen Stewart','Cristina Ricci','Emma Watson','Dakota Fanning',NOW(),NOW()),
('ENTRETENIMIENTO','¿Cómo se llamaba el personaje que interpretaba Al Pacino en "Scarface"?','Tony Montana','Michael Corleone','Frank Slade','Sonny Montana',NOW(),NOW()),
('ENTRETENIMIENTO','¿A qué película de Disney pertenece la canción "Un mundo ideal"?','Aladdín','Pocahontas','Mulán','Hércules',NOW(),NOW()),
('ENTRETENIMIENTO','¿A qué hace referencia "La milla verde"?','Al corredor de la muerte','A la cárcel','A un prado cercano','A una carrera',NOW(),NOW()),
('ENTRETENIMIENTO','¿Quién interpreta la canción "Baby One More Time"?','Britney Spears','Lady Gaga','Montserrat Caballé','Madonna',NOW(),NOW()),
('ENTRETENIMIENTO','¿A quién se considera el Rey del Pop?','Michael Jackson','Justin Bieber','Zayn Malik','Zac Efron',NOW(),NOW()),
('ENTRETENIMIENTO','¿Qué personaje del videojuego Mortal Kombat tiene poderes de hielo?','Sub-Zero','Scorpion','Reptile','Motaro',NOW(),NOW()),
('ENTRETENIMIENTO','¿Qué día es San Valentín?','14 de Febrero','15 de Febrero','14 de Marzo','15 de Marzo',NOW(),NOW()),
('ENTRETENIMIENTO','¿Cómo se llamaba el primer gato de Los Simpsons?','Bola de nieve','Bola','Gaturro','Nevu',NOW(),NOW()),
('ENTRETENIMIENTO','¿Cuáles son los nombres de "Los Tres Chiflados"?','Moe, Larry y Curly','Mou, Larri y Carly','Bart, Luck y Loles','Mio, Luck, Patrick',NOW(),NOW()),
('ENTRETENIMIENTO','¿Qué quería comerse Alf?','Al gato','Las plantas','A Lynn','A Willie',NOW(),NOW()),
('ENTRETENIMIENTO','¿Cómo se llama el ayudante de Iron Man?','Jarvis','Alex','Jef','Carlitos',NOW(),NOW()),
('ENTRETENIMIENTO','¿En qué película se dice "La vida es como una caja de bombones, nunca sabes qué te va a tocar"?','Forrest Gump','Matrix','Spiderman','Airbag',NOW(),NOW()),
('ENTRETENIMIENTO','¿Qué personaje Disney baja por un río con una canoa?','Pocahontas','Blancanieves','Peter Pan','Lilo y Stich',NOW(),NOW()),
('ENTRETENIMIENTO','¿Cómo se llama el juguete que es un cubo de colores el cual giran sus partes?','Rubik','Spinner','Magic','Multicolor',NOW(),NOW()),
('ENTRETENIMIENTO','¿Cuál fué la primera película de Disney?','Blancanieves','La sirenita','La bella y la Bestia','La cenicienta',NOW(),NOW()),
('ENTRETENIMIENTO','¿Quién era Jay-Jay?','Un avioncito','Un autito','Un trencito','Una bicicleta',NOW(),NOW()),
('ENTRETENIMIENTO','¿Qué es Assasins Creed?','Un videojuego','Un pais','Una secta','Una tienda de ropa',NOW(),NOW()),
('ENTRETENIMIENTO','¿Cómo se llama el actor que interpreta a Michael en la película "El padrino"?','Al Pacino','James Caan','Robert Duvall','Marlon Brando',NOW(),NOW()),
('CIENCIAS','¿De qué color es la sange de los peces?','Roja','Verde Oscuro','Azul','Marron',NOW(),NOW()),
('CIENCIAS','¿Por qué los cocodrilos mantienen la boca abierta durante largo rato?','Para calentarse','Para hacer la digestión','Para beber agua','Para esperar una presa',NOW(),NOW()),
('CIENCIAS','¿Con qué abren las ostras las nutrias de mar?','Con una piedra','Con los dientes','Con un palo','Con las uñas',NOW(),NOW()),
('CIENCIAS','¿Cuanto de los sig numeros es Capicua?','121','154','1002','450',NOW(),NOW()),
('CIENCIAS','¿Cuantos dientes tiene un pingüino promedio?','Ninguno','12','20','10',NOW(),NOW()),
('CIENCIAS','¿Por qué se arrugan los dedos bajo el agua?','Para mejorar el agarre de cuerpos húmedos','Porque el agua filtra en la capa exterior de la piel','Para absorver más nutrientes','Para evitar quemarnos',NOW(),NOW()),
('CIENCIAS','¿Por qué sudamos cuando hace calor?','Para regular la temperatura corporal','Para ahuyentar a los mosquitos','Para evitar el cansancio','Para correr más',NOW(),NOW()),
('CIENCIAS','¿Cuánta sangre tiene un ser humano aproximadamente?','Entre 4,5 y 6 litros','1 litro','7 litros','10 litros',NOW(),NOW()),
('CIENCIAS','¿Cómo llamamos al latido del corazón?','Impulso cardíaco','Bombeo','Latido','Propulsión',NOW(),NOW()), 
('CIENCIAS','¿Qué función tienen las proteinas?','Constructiva','Reguladora','Anabolizante','Energética',NOW(),NOW()), 
('CIENCIAS','¿Cuál de estas es una enfermedad mental relacionada con la nutrición?','Anorexia','Obesidad','Escorbuto','Raquitismo',NOW(),NOW()), 
('CIENCIAS','¿Cuál es el resultado de sumar una 1 hora y 40 minutos y 1 hora y 30 minutos?','3 horas y 10 minutos','3 horas','1 hora y 40 minutos','2 horas y 50 minutos',NOW(),NOW()),
('CIENCIAS','¿Cuántos lados tiene un hexágono?','6','7','9','5',NOW(),NOW()),
('CIENCIAS','¿Qué es más ligero?','100 gramos de hierro','1 kilo de plumas','1 kilo de lana','1 kilo de algodón',NOW(),NOW()),
('CIENCIAS','Qué inventaron los hermanos Lumiéres','El cine','El automovil','El teléfono','La electricidad',NOW(),NOW()),
('CIENCIAS','¿Cuántos días tiene un año bisiesto?','366','345','365','367',NOW(),NOW()),
('CIENCIAS','¿Cómo se llama la escritura utilizada por personas ciegas?','Braille','Jeroglífico','Morse','Ideograma',NOW(),NOW()),
('CIENCIAS','¿Cuántas manos tiene un caballo?','2','4','8','6',NOW(),NOW()),
('CIENCIAS','¿Cuáles son las dos primeras palabras de la Biblia?','Al Principio','Fue aquél','Todo Comenzó','Las cosas',NOW(),NOW()),
('CIENCIAS','¿Qué órgano segrega la hormona insulina?','El páncreas','El hígado','Los pulmones','El corazón',NOW(),NOW()),
('CIENCIAS','¿Cuál es la moneda de Suiza?','franco Suizo','euro','dolar','dolar blue',NOW(),NOW()),
('CIENCIAS','¿Cuál de las sisguientes enfermedades ataca al higado?','Hepatitis','Diabetes','Artrósis','Cifoescoliosis',NOW(),NOW()),
('CIENCIAS','¿Cuál es la función principal del instestino grueso?','La absorción de agua','La digestión química de alimentos','La digestión química de alimentos','La absorción de nutrientes',NOW(),NOW()),
('CIENCIAS','¿Qué cambio de estado ocurre en la sublimación?','De sólido a gaseoso','De sólido a líquido','De gaseoso a líquido','De líquido a solido',NOW(),NOW()),
('CIENCIAS','¿Qué órgano del cuerpo humano produce la bilis?','Hígado','Páncreas','Intestino delgado','Riñon',NOW(),NOW()),
('CIENCIAS','¿De qué color es la sange de los peces?','Rojo','Azul','Celeste','Marrón oscuro',NOW(),NOW()),
('CIENCIAS','Cuál de los siguientes órganos NO es parte del sistema inmunológico?','Esófago','Médula Ósea','Bazo','Timo',NOW(),NOW()),
('CIENCIAS','¿Cuántas caras tiene un icosaedro?','20','16','8','24',NOW(),NOW()),
('CIENCIAS','¿Qué se altera cuando nos damos un golpe en la cabeza que nos hace "ver las estrellas"?','El nervio óptico','La pituitaria','El bulbo raquídeo','El hipotálamo',NOW(),NOW()),
('CIENCIAS','¿Cuál es el hueso más pequeño del cuerpo?','El estribo','La falange','Ninguna es correcta','El yunque',NOW(),NOW()),
('CIENCIAS','¿Qué estudia la icitología?','Los peces','Los insectos','Las rocas','Las erupciones cutáneas',NOW(),NOW()),
('CIENCIAS','¿Cuál es el mamífero más grande conocido hasta la actualidad?','Ballena azul','Elefante','Rinoceronte','Cachalote',NOW(),NOW()),
('CIENCIAS','Un equino es..','Un caballo','Una vaca','Una oveja','Un antílope',NOW(),NOW()),
('CIENCIAS','¿Con qué otro nombre se conoce el ciclo del agua?','Ciclo hidrológico','Ciclo acuoso','Ciclo natural','Ciclo hidropónico',NOW(),NOW()),
('CIENCIAS','¿Qué animal representa al Sistema Operativo Linux?','Pingüino','León','Panda','Leopardo',NOW(),NOW()),
('CIENCIAS','¿Qué son los triglicéridos?','Lípidos','Glúcidos','Proteínas','Vitaminas',NOW(),NOW()),
('CIENCIAS','¿Qué es la hemofobia?','Miedo a la sangre','Miedo a las alturas','Ninguna es correcta','Miedo al agua',NOW(),NOW()),
('CIENCIAS','¿Cuál es el nombre del compuesto cuya formula es H2SO4?','Ácido sulfúrico','Ácido sulfuroso','Ácido sulfhídrico','Anhídrido sulfuroso',NOW(),NOW()),
('CIENCIAS','¿Qué líquido almacenan los cactus?','Agua','Vino','Miel','Savia',NOW(),NOW()),
('CIENCIAS','¿Cuál es la combinación de las teclas que copia texto en un PC?','Ctrl + c','Ctrl + v','Ctrl + z','Ctrl + n',NOW(),NOW()),
('CIENCIAS','¿Cómo se conoce el ingrediente psicoactivo de la marihuana?','THC','LSD','PHP','LHC',NOW(),NOW()),
('CIENCIAS','¿Cómo se llama la rama de las matemáticas en que los números son representados por letras y símbolos?','Álgebra','Adición','Geometría','Topología',NOW(),NOW()),
('CIENCIAS','¿Cuál es el animal que tiene la presión más alta?','Jirafa','Conejo','Serpiente','Elefante',NOW(),NOW()),
('CIENCIAS','¿De qué color es el sudor de los hipopótamos?','Rojizo','Amarillo','Celeste','Verde',NOW(),NOW()),
('CIENCIAS','¿Cómo se llama el líquido que expulsan los recién nacidos en lugar de las heces durante los primeros días?','Meconio','Placenta','Frutenio','Politu',NOW(),NOW()),
('CIENCIAS','¿Cuál es la planta más conocida que tiene propiedades cicatrizantes,limpiadoras y regeneradoras?','Aloe Vera','Alcachofa','Eneldo','Quínoa',NOW(),NOW()),
('CIENCIAS','¿Cómo conocemos comunmente al compuesto químico H2O2?','Agua oxigenada','Agua fuerte','Agua pesada','Aguarrás',NOW(),NOW()),
('CIENCIAS','¿Qué es el esternocleidomastoideo?','Un músculo','Un tendón','Un ligamento','Un hueso',NOW(),NOW()),
('CIENCIAS','¿Qué animal puede correr sobre el agua?','Lagarto basilisco','Lagartija','Pato','Ninguno',NOW(),NOW()),
('CIENCIAS','¿Quién formuló la teoría de la relatividad general?','Albert Einstein','Isaac Newton','Erwin Schrodinger','Stephen Hawking',NOW(),NOW()),
('CIENCIAS','¿Cómo se llama la técnica de cultivo de especies acuáticas vegetales y animales?','Acuicultura','Apicultura','Aguacultura','Hidrocultura',NOW(),NOW()),
('CIENCIAS','¿Qué hormona representa la abreviatura T4?','Tiroxina','Tiroglobulina','Tirosina','Tetrayoduro',NOW(),NOW()),
('CIENCIAS','¿Qué codificación utiliza solamente 0 y 1?','Binario','Octal','Decimal','Hexadecimal',NOW(),NOW()),
('GEOGRAFIA','¿Con cuántos países limita Argentina?','5','4','6','3',NOW(),NOW()),
('GEOGRAFIA','¿En qué país está Ushuaia, la ciudad más al sur del mundo?','Argentina','Chile','Sudáfrica','Nueva Zelanda',NOW(),NOW()),
('GEOGRAFIA','¿A qué país pertenece la isla Mujeres? ','Mexico','Argentina','Colombia','Chile',NOW(),NOW()),
('GEOGRAFIA','¿Cuál es el idioma oficial de Uruguay?','Español','Uruguayo','Guarani','Español y Uruguayo',NOW(),NOW()),
('GEOGRAFIA','¿En qué continente podemos encontrar Senegal?','África','Oceanía','Asia','Europa',NOW(),NOW()), 
('GEOGRAFIA','¿En qué cadena montañosa encontramos la cima más alta del mundo?','El Himalaya','Los Alpes','Los Andes','Los Cárpatos',NOW(),NOW()), 
('GEOGRAFIA','¿Cuál es la capital de China?','Pekín','Hong Kong','Tokio','Seúl',NOW(),NOW()),
('GEOGRAFIA','¿Cuál de las siguientes ciudades no tiene mar?','París','Barcelona','Palermo','Valencia',NOW(),NOW()),
('GEOGRAFIA','¿Qué país de los siguientes no hace frontera con Francia?','Portugal','Suiza','España','Italia',NOW(),NOW()),
('GEOGRAFIA','¿Cuál es la capital de Dinamarca?','Copenhague','Helsinki','Estocolmo','Oslo',NOW(),NOW()), 
('GEOGRAFIA','¿Dónde podemos encontrar la Estatua de la Libertad?','Nueva York','Washington','Los Angeles','Chicago',NOW(),NOW()),
('GEOGRAFIA','¿En qué ciudad se encuentra el museo del Louvre?','París','Madrid','Roma','Milán',NOW(),NOW()),
('GEOGRAFIA','¿En qué país encontraremos la Basílica de San Pedro?','Ciudad del Vaticano','España','Francia','Italia',NOW(),NOW()),
('GEOGRAFIA','¿A qué país pertenece la isla de Tasmania?','Australia','Estados Unidos','Portugal','Ninguna es correcta',NOW(),NOW()),
('GEOGRAFIA','¿En qué país situarías la ciudad de Cali?','Colombia','Perú','Brasil','Costa Rica',NOW(),NOW()),
('GEOGRAFIA','¿Cuál de estas características no pertenece al clima Mediterráneo?','Lluvias muy abundantes','Veranos secos y calurosos','Es un tipo de clima templado','Variables temperaturas en primavera',NOW(),NOW()),
('GEOGRAFIA','¿Qué es el Cabo de Creus?','El punto más oriental de la Península','El punto más oriental de España','El punto más oriental de Cataluña','Ninguna es correcta',NOW(),NOW()),
('GEOGRAFIA','¿Qué es la UA?','Unión Africana','Unión Austrohúngara','Unión Americana','Unión Afroamericana',NOW(),NOW()),
('GEOGRAFIA','¿Qué separa las franjas de Gaza y Cisjordania?','Israel','Un muro','Nada','Un rio',NOW(),NOW()),
('GEOGRAFIA','¿Cuál de estos países africanos no tiene costa?','Todas tienen costa','Mauritania','Senegal','Gambia',NOW(),NOW()),
('GEOGRAFIA','¿En qué se dividen las rupias indias y pakistanís?','En paisas','En peniques','En céntimos','En centavos',NOW(),NOW()),
('GEOGRAFIA','¿Cuál de las siguientes islas está más al sur?','Malta','Sicilia','Córcega','Cerdeña',NOW(),NOW()),
('GEOGRAFIA','¿En qué país está la Laguna Verde?','Bolivia','Chile','Todas son correctas','Argentina',NOW(),NOW()),
('GEOGRAFIA','¿Qué ciudad europea es famosa por la belleza de su parlamento?','Budapest','París','Madrid','Praga',NOW(),NOW()),
('GEOGRAFIA','¿Qué accidente geográfico se define como un conjunto de islas, islotes y diminutas masas de tierra cercanas entre sí? ','Archipiélago','Península','Islotes','Meandro',NOW(),NOW()),
('GEOGRAFIA','¿A qué país pertenece la isla Mujeres?','México','Argentina','Colombia','Chile',NOW(),NOW()),
('GEOGRAFIA','¿Qué país africano fue antigua colonia española?','Guinea Ecuatorial','Congo','Sudáfrica','Egipto',NOW(),NOW()),
('GEOGRAFIA','¿Cuál es la religión mayoritaria en China?','Budismo','Taoísmo','Confucianismo','Cristianismo',NOW(),NOW()),
('GEOGRAFIA','¿Que accidente geográfico se define como una pendiente vertical abrupta?','Un acantilado','Un barranco','Una montaña','Un puente',NOW(),NOW()),
('GEOGRAFIA','¿Dónde se encuentra el Cerro Uritorco, conocido por sus avistamientos a O.V.N.I.S.?','Al sur de Mongolia','Al sur de China','Al sur de Japón','Ninguna es correcta',NOW(),NOW()),
('GEOGRAFIA','¿A qué país pertenece la Isla de Pascua?','Chile','Indonesia','Australia','Es un país',NOW(),NOW()),
('GEOGRAFIA','¿En qué país europeo está la ciudad de Lyon?','En Francia','En Italia','En Luxemburgo','En Bélgica',NOW(),NOW()),
('GEOGRAFIA','¿Dónde hay mayor número de habitantes?','China','Estados Unidos','Alemania','Rusia',NOW(),NOW()),
('GEOGRAFIA','¿A qué país pertenece la Camorra?','Italia','Francia','España','Grecia',NOW(),NOW()),
('GEOGRAFIA','¿Cuál es la cuidad gallega más poblada?','Vigo','A Coruña','Santiago de Compostela','Ourense',NOW(),NOW()),
('GEOGRAFIA','¿De dónde es tradicional la paella?','Comunidad Valenciana','Cataluña','Andalucía','País Vasco',NOW(),NOW()),
('GEOGRAFIA','¿De qué estado mexicano es originaria el Tequila?','Jalisco','Nayarit','Michoacán','Guanajuato',NOW(),NOW()),
('GEOGRAFIA','¿Cuál es el único país latinoamericano que tiene 2 lenguas oficiales?','Paraguay','Argentina','Venezuela','Brasil',NOW(),NOW()),
('GEOGRAFIA','¿Cuál es el río más caudaloso del mundo?','El Amazonas','El Nilo','El Congo','El Orinoco',NOW(),NOW()),
('GEOGRAFIA','¿Dónde desemboca el Río Magdalena?','En el mar Caribe','En el golfo de México','En el océano Atlántico','En el océano Pacífico',NOW(),NOW()),
('GEOGRAFIA','¿Cuál es el océano más grande del mundo?','Océano Pacífico','Océano Antártico','Océano Índico','Océano Atlántico',NOW(),NOW()),
('GEOGRAFIA','¿Cuál es la capital de Corea del Sur?','Seul','Pyongyang','Phnom Phen','Riad',NOW(),NOW()),
('GEOGRAFIA','¿A qué municipio pertenece el cabo de Gata?','Nijar','Nebrija','Cádiz','Málaga',NOW(),NOW()),
('HISTORIA','¿Cómo se conoce a la escritura del Antiguo Egipto?','Jeroglíficos','Cirílica','Romana','Hebraica',NOW(),NOW()),
('HISTORIA','¿Qué pueblo mandaba Atila?','Los Hunos','Los romanos','Los galos','Los vikingos',NOW(),NOW()),
('HISTORIA','¿Cuál es la ciudad más antigua de América Latina?','Caral','Valparaíso','La Paz','Arequipa',NOW(),NOW()),
('HISTORIA','¿Cuántos soldados argentinos murieron en la Guerra de las Malvinas?','649','200','1100','1964',NOW(),NOW()),
('HISTORIA','¿Quién pronunció la frase: "Bebamos de la copa de la destrucción"?','Gengis Kan','Mussolini','Margaret Tatcher','Berlusconi',NOW(),NOW()),
('HISTORIA','¿Con qué emperador estuvo casada Cleopatra?','Todas son correctas','Ptolomeo XIV','Marco Antonio','Julio César',NOW(),NOW()),
('HISTORIA','El Renacimiento marcó el inicio de la Edad..','Moderna','Media','Contemporánea','Antigüedad clásica',NOW(),NOW()),
('HISTORIA','¿Qué se celebra el 8 de Marzo?','El día de la mujer','El día del medio ambiente','El día del niño','El día del trabajo',NOW(),NOW()),
('HISTORIA','¿Cuántos siglos duró el Siglo de Oro?','2','1','3','5',NOW(),NOW()),
('HISTORIA','¿Qué fue Dracón?','Legislador','Comerciante','Médico','Guerrero',NOW(),NOW()),
('HISTORIA','¿Qué otro nombre recibió la Primera Guerra Mundial hasta 1939?','La Gran Guerra','La Guerra de los 100 años','La Guerra entre las Guerras','Ningún otro',NOW(),NOW()),
('HISTORIA','¿En qué año viajó el primer hombre a la luna?','1969','1968','1985','1945',NOW(),NOW()),
('HISTORIA','¿En qué año empezó la Guerra del Golfo Pérsico?','1990','1980','1995','1985',NOW(),NOW()),
('HISTORIA','¿En qué año sucedió el Accidente de Chernóbil?','1986','1985','1987','1988',NOW(),NOW()),
('HISTORIA','¿En qué año fué el último enfrentamiento bélico por las Islas Malvinas entre Argentina e Inglaterra?','1982','1975','1976','1984',NOW(),NOW()),
('HISTORIA','¿Qué evento histórico da comienzo a la Edad Contemporánea?','La Revolución Francesa','La caída del Imperio Romano de Occidente','La Guerra de los 100 años','Guerra de Independencia',NOW(),NOW()),
('HISTORIA','¿En qué año tuvo lugar el ataque a Pearl Harbor?','1941','1939','1940','1942',NOW(),NOW()),
('HISTORIA','¿Quién liberó a Argentina, Chile y Perú?','José de San Martín','Simón Bolívar','Ernesto ‘Che’ Guevara','Manual Belgrano',NOW(),NOW()),
('HISTORIA','¿Qué motivó la rebelión que dio lugar a la Guerra de la Independencia de EEUU?','Impuesto','Corrupción','Represión','Esclavitud',NOW(),NOW()),
('HISTORIA','¿Qué imperio llegó a conquistar casí toda Europa?','Romano','Cartago','Espartano','Vikingo',NOW(),NOW());
('HISTORIA','¿Qué día y año se declaró la independencia nacional?','9 de julio de 1816','25 de mayo de 1810','1 de mayo de 1810','17 de agosto de 1816',NOW(),NOW());
('HISTORIA','¿Qué sucedió en Argentina el 26 de junio de 1821 ?','Nacimiento de Bartolomé Mitre','Inauguracion de la primer cancha de futbol en Bs As','Muerte de Mariano Moreno','Reforma de la constitucion Argentina',NOW(),NOW());
('HISTORIA','¿Quién fue elegido gobernador de Bs As en 1827?','Manuel Dorrego','Juan Manuel de Rosas','Manuel de Sarratea','Domingo Faustino Sarmiento',NOW(),NOW());
('HISTORIA','¿En qué año ocuparon los ingleses las Islas Malvinas?','1833','1843','1976','1855',NOW(),NOW());
('HISTORIA','¿En que lugar y año fue asesinado Facundo Quiroga?','1835 Barranca Yaco','1801 Yapeyú','1903 La Rioja','1920 Buenos Aires',NOW(),NOW());
('HISTORIA','¿Qué prócer falleció el 17 de agosto de 1850?','José de San Martin','Julio Argentino Roca','Domingo Sarmiento','Manuel Belgrano',NOW(),NOW());
('HISTORIA','¿Quien asume la presidencia Argentina en 1868?','Domingo Sarmiento','Hipólito Yrigoyen','Roque Sáenz Peña','Jose de San Martin',NOW(),NOW());
('HISTORIA','¿Cuando se inauguró el telégrafo entre Buenos Aires y Rosario?','1° de mayo 1869','1870 Primera comunicacion','1903 duró solo un minuto','1950 duró 15 segundos',NOW(),NOW());
('HISTORIA','¿En qué año se transforma la ciudad de Buenos Aires en Capital de la República?','20 de septiembre 1880','20 de septiembre 1890','1 de marzo 1994','5 de agosto 1840',NOW(),NOW());
('HISTORIA','¿Que importante club de futbol se fundó el 25 de mayo de 1901?','River Plate','Boca Juniors','Independiente de avellaneda','Racing Club de Avellaneda',NOW(),NOW());
('HISTORIA','¿En qué año flameó por primera vez la banbera argentina en la Antártida?','22 de febrero 1904','15 de enero 1910','28 de julio 1914','14 de mayo de 1890',NOW(),NOW());
('HISTORIA','¿Que importante teatro se inaugura en Buenos Aires el 25 de mayo de 1908?','Teatro Colón','Teatro Cervantes','Teatro San Martin','Teatro Opera',NOW(),NOW());
('HISTORIA','¿Cuántos ex presidentes de Argentina han sido asesinados?','2','5','Ninguno','4',NOW(),NOW());
('HISTORIA','¿Cuántos presidentes constitucionales hubo en la Argentina desde 1983?','9','5','13','20',NOW(),NOW());
('HISTORIA','¿Que ícono argentino fallece en un accidente de avión el 24 de junio 1935?','Carlos Gardel, en Colombia','Ernesto "Che" Guevara, en Bolivia','Raúl Alfonsín, en Paraguay','Domingo Sarmiento, en Perú',NOW(),NOW());

